/**
 * Report Generator
 *
 * Produces .gitnexus/assessment-report.md and .gitnexus/assessment-report.json
 * from dead code analysis, metrics, and modernization scoring results.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import type { DeadCodeResults } from './dead-code.js';
import type { MetricsResult } from './metrics.js';
import type { ModernizationResult } from './mod-scorer.js';

export interface JclSummary {
  jobCount: number;
  stepCount: number;
  datasetCount: number;
  programLinks: number;
}

export interface ReportOptions {
  repoName: string;
  outputDir: string;
  format: 'markdown' | 'json' | 'both';
  detailed: boolean;
  deadCode: DeadCodeResults;
  metrics: MetricsResult;
  modernization: ModernizationResult;
  jcl?: JclSummary;
}

export interface ReportResult {
  markdownPath?: string;
  jsonPath?: string;
}

/**
 * Generate assessment report files.
 */
export async function generateReport(options: ReportOptions): Promise<ReportResult> {
  const result: ReportResult = {};

  await fs.mkdir(options.outputDir, { recursive: true });

  if (options.format === 'markdown' || options.format === 'both') {
    const md = generateMarkdown(options);
    const mdPath = path.join(options.outputDir, 'assessment-report.md');
    await fs.writeFile(mdPath, md, 'utf-8');
    result.markdownPath = mdPath;
  }

  if (options.format === 'json' || options.format === 'both') {
    const json = generateJson(options);
    const jsonPath = path.join(options.outputDir, 'assessment-report.json');
    await fs.writeFile(jsonPath, JSON.stringify(json, null, 2), 'utf-8');
    result.jsonPath = jsonPath;
  }

  return result;
}

function generateMarkdown(opts: ReportOptions): string {
  const { repoName, deadCode, metrics, modernization, jcl, detailed } = opts;
  const lines: string[] = [];
  const ln = (s: string = '') => lines.push(s);

  ln(`# Modernization Assessment: ${repoName}`);
  ln();
  ln(`> Generated by GitNexus on ${new Date().toISOString().split('T')[0]}`);
  ln();

  // Executive Summary
  ln(`## Executive Summary`);
  ln();
  ln(`| Metric | Value |`);
  ln(`|--------|-------|`);
  ln(`| Overall Readiness Score | **${modernization.overallScore}/100** |`);
  ln(`| Dead Code | ${deadCode.summary.deadCodePct.toFixed(1)}% |`);
  ln(`| Extraction Candidates | ${modernization.candidates.filter(c => c.recommendation === 'extract').length} communities |`);
  ln(`| Refactor-First | ${modernization.candidates.filter(c => c.recommendation === 'refactor-first').length} communities |`);
  ln(`| Leave-In-Place | ${modernization.candidates.filter(c => c.recommendation === 'leave-in-place').length} communities |`);
  ln(`| Total Programs | ${metrics.global.totalPrograms} |`);
  ln(`| Total Paragraphs | ${metrics.global.totalParagraphs} |`);
  ln(`| Total Communities | ${metrics.global.totalCommunities} |`);
  ln();

  // 1. Dead Code Analysis
  ln(`## 1. Dead Code Analysis`);
  ln();
  ln(`### Summary`);
  ln();
  ln(`- **Unused paragraphs**: ${deadCode.summary.unusedCount} of ${deadCode.summary.totalParagraphs}`);
  ln(`- **Unreachable programs**: ${deadCode.summary.unreachableCount}`);
  ln(`- **Orphan copybooks**: ${deadCode.summary.orphanCount}`);
  ln();

  if (deadCode.unreachablePrograms.length > 0) {
    ln(`### Unreachable Programs`);
    ln();
    ln(`| Program | File |`);
    ln(`|---------|------|`);
    const displayProgs = detailed ? deadCode.unreachablePrograms : deadCode.unreachablePrograms.slice(0, 50);
    for (const p of displayProgs) {
      ln(`| ${p.name} | ${p.filePath} |`);
    }
    if (!detailed && deadCode.unreachablePrograms.length > 50) {
      ln(`| ... | *${deadCode.unreachablePrograms.length - 50} more (use --detailed)* |`);
    }
    ln();
  }

  if (deadCode.unusedParagraphs.length > 0) {
    ln(`### Unused Paragraphs (top 50)`);
    ln();
    ln(`| Paragraph | Program | File | Line |`);
    ln(`|-----------|---------|------|------|`);
    const displayParas = detailed ? deadCode.unusedParagraphs : deadCode.unusedParagraphs.slice(0, 50);
    for (const p of displayParas) {
      ln(`| ${p.name} | ${p.programName} | ${p.filePath} | ${p.line} |`);
    }
    if (!detailed && deadCode.unusedParagraphs.length > 50) {
      ln(`| ... | | | *${deadCode.unusedParagraphs.length - 50} more* |`);
    }
    ln();
  }

  if (deadCode.orphanCopybooks.length > 0) {
    ln(`### Orphan Copybooks`);
    ln();
    ln(`| Name | File |`);
    ln(`|------|------|`);
    const displayCopy = detailed ? deadCode.orphanCopybooks : deadCode.orphanCopybooks.slice(0, 50);
    for (const c of displayCopy) {
      ln(`| ${c.name} | ${c.filePath} |`);
    }
    if (!detailed && deadCode.orphanCopybooks.length > 50) {
      ln(`| ... | *${deadCode.orphanCopybooks.length - 50} more* |`);
    }
    ln();
  }

  // 2. Complexity & Coupling
  ln(`## 2. Complexity & Coupling`);
  ln();
  ln(`### Global Metrics`);
  ln();
  ln(`| Metric | Value |`);
  ln(`|--------|-------|`);
  ln(`| Avg Fan-In | ${metrics.global.avgFanIn.toFixed(1)} |`);
  ln(`| Avg Fan-Out | ${metrics.global.avgFanOut.toFixed(1)} |`);
  ln(`| Max Fan-In | ${metrics.global.maxFanIn} |`);
  ln(`| Max Fan-Out | ${metrics.global.maxFanOut} |`);
  ln(`| Max PERFORM Depth | ${metrics.global.maxPerformDepth} |`);
  ln();

  // Top programs by fan-out
  const topFanOut = [...metrics.programs].sort((a, b) => b.fanOut - a.fanOut).slice(0, 20);
  if (topFanOut.length > 0) {
    ln(`### Top Programs by Fan-Out`);
    ln();
    ln(`| Program | Fan-Out | Fan-In | Paragraphs | COPYs | EXEC SQL | EXEC CICS |`);
    ln(`|---------|---------|--------|------------|-------|----------|-----------|`);
    for (const p of topFanOut) {
      ln(`| ${p.name} | ${p.fanOut} | ${p.fanIn} | ${p.paragraphCount} | ${p.copyCount} | ${p.execSqlCount} | ${p.execCicsCount} |`);
    }
    ln();
  }

  // Top programs by fan-in
  const topFanIn = [...metrics.programs].sort((a, b) => b.fanIn - a.fanIn).slice(0, 20);
  if (topFanIn.length > 0) {
    ln(`### Top Programs by Fan-In`);
    ln();
    ln(`| Program | Fan-In | Fan-Out |`);
    ln(`|---------|--------|---------|`);
    for (const p of topFanIn) {
      ln(`| ${p.name} | ${p.fanIn} | ${p.fanOut} |`);
    }
    ln();
  }

  // Most shared copybooks
  const topCopybooks = [...metrics.copybooks].sort((a, b) => b.fanIn - a.fanIn).slice(0, 20);
  if (topCopybooks.length > 0) {
    ln(`### Most Shared Copybooks`);
    ln();
    ln(`| Copybook | Used By (programs) |`);
    ln(`|----------|-------------------|`);
    for (const c of topCopybooks) {
      ln(`| ${c.name} | ${c.fanIn} |`);
    }
    ln();
  }

  // Community coupling
  if (metrics.communities.length > 0) {
    ln(`### Community Coupling`);
    ln();
    ln(`| Community | Cohesion | Internal | External | Coupling Ratio |`);
    ln(`|-----------|----------|----------|----------|---------------|`);
    for (const c of metrics.communities.slice(0, 30)) {
      ln(`| ${c.label} | ${(c.cohesion * 100).toFixed(0)}% | ${c.internalEdges} | ${c.externalEdges} | ${(c.couplingRatio * 100).toFixed(0)}% |`);
    }
    ln();
  }

  // 3. JCL Job Streams
  if (jcl && (jcl.jobCount > 0 || jcl.stepCount > 0)) {
    ln(`## 3. JCL Job Streams`);
    ln();
    ln(`| Metric | Value |`);
    ln(`|--------|-------|`);
    ln(`| Jobs | ${jcl.jobCount} |`);
    ln(`| Steps | ${jcl.stepCount} |`);
    ln(`| Datasets | ${jcl.datasetCount} |`);
    ln(`| Step-to-Program Links | ${jcl.programLinks} |`);
    ln();
  }

  // 4. Modernization Candidates
  ln(`## 4. Modernization Candidates`);
  ln();
  ln(`### Ranked by Isolation Score`);
  ln();
  ln(`| # | Community | Score | Programs | Recommendation |`);
  ln(`|---|-----------|-------|----------|---------------|`);
  for (let i = 0; i < modernization.candidates.length; i++) {
    const c = modernization.candidates[i];
    const emoji = c.recommendation === 'extract' ? 'EXTRACT' :
                  c.recommendation === 'refactor-first' ? 'REFACTOR' : 'IN-PLACE';
    ln(`| ${i + 1} | ${c.label} | ${c.isolationScore} | ${c.programs.length} | ${emoji} |`);
  }
  ln();

  // Detailed breakdown for extraction candidates
  const extractCandidates = modernization.candidates.filter(c => c.recommendation === 'extract');
  if (extractCandidates.length > 0) {
    ln(`### Extraction Candidates (Detail)`);
    ln();
    for (const c of extractCandidates) {
      ln(`#### ${c.label} (Score: ${c.isolationScore})`);
      ln();
      ln(`${c.rationale}`);
      ln();
      ln(`| Factor | Score |`);
      ln(`|--------|-------|`);
      ln(`| Cohesion | ${c.breakdown.cohesion}% |`);
      ln(`| Decoupling | ${c.breakdown.decoupling}% |`);
      ln(`| Copybook Isolation | ${c.breakdown.copybookIsolation}% |`);
      ln(`| Complexity | ${c.breakdown.complexity}% |`);
      ln(`| Dead Code | ${c.breakdown.deadCode}% |`);
      ln(`| JCL Isolation | ${c.breakdown.jclIsolation}% |`);
      ln();
      if (detailed && c.programs.length > 0) {
        ln(`Programs: ${c.programs.join(', ')}`);
        ln();
      }
    }
  }

  return lines.join('\n');
}

function generateJson(opts: ReportOptions): object {
  return {
    repoName: opts.repoName,
    generatedAt: new Date().toISOString(),
    summary: {
      overallScore: opts.modernization.overallScore,
      deadCodePct: opts.deadCode.summary.deadCodePct,
      extractCandidates: opts.modernization.candidates.filter(c => c.recommendation === 'extract').length,
      refactorFirst: opts.modernization.candidates.filter(c => c.recommendation === 'refactor-first').length,
      leaveInPlace: opts.modernization.candidates.filter(c => c.recommendation === 'leave-in-place').length,
    },
    deadCode: opts.deadCode,
    metrics: {
      global: opts.metrics.global,
      programs: opts.detailed ? opts.metrics.programs : opts.metrics.programs.slice(0, 100),
      copybooks: opts.detailed ? opts.metrics.copybooks : opts.metrics.copybooks.slice(0, 100),
      communities: opts.metrics.communities,
    },
    modernization: opts.modernization,
    jcl: opts.jcl ?? null,
  };
}
